# Generated by Django 4.0.3 on 2022-03-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendrequest_friendlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
